version: '3.8'

services:
  ssrf-app:
    build: .
    container_name: ssrf-lab-ctf
    ports:
      - "8041:80"
    restart: unless-stopped
    networks:
      ssrf-ctf-network:
        ipv4_address: 172.31.0.10
      tracking-network:
    extra_hosts:
      - "tracking-service:host-gateway"

  internal-api:
    build: ./internal-api
    container_name: internal-api
    restart: unless-stopped
    # No external ports - only accessible from within Docker network!
    networks:
      ssrf-ctf-network:
        ipv4_address: 172.31.0.50
        aliases:
          - internal-api
          - metadata.internal
          - db.internal

networks:
  ssrf-ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
  tracking-network:
    external: true
