version: '3.8'

services:
  api-security-lab:
    build: .
    container_name: api-security-lab
    ports:
      - "8062:80"
    volumes:
      - ./logs:/var/log/apache2
    restart: unless-stopped
    networks:
      - lab-network
      - tracking-network

networks:
  lab-network:
    driver: bridge
  tracking-network:
    external: true
