worker_processes auto;

events { worker_connections 1024; }

http {

upstream lab_e1 { server lab_e1_web:80; }
upstream lab_e2 { server lab_e2_web:80; }
upstream lab_e3 { server lab_e3_web:80; }
upstream lab_e4 { server lab_e4_web:80; }
upstream lab_e5 { server lab_e5_web:80; }
upstream lab_e6 { server lab_e6_web:80; }
upstream lab_m1 { server lab_m1_web:80; }
upstream lab_m2 { server lab_m2_web:80; }
upstream lab_m3 { server lab_m3_web:80; }
upstream lab_m4 { server lab_m4_web:80; }
upstream lab_m5 { server lab_m5_web:80; }
upstream lab_h1 { server lab_h1_web:80; }
upstream lab_h2 { server lab_h2_web:80; }
upstream lab_h3 { server lab_h3_web:80; }
upstream lab_h4 { server lab_h4_web:80; }
upstream lab_h5 { server lab_h5_web:80; }
# upstream articles { server articles-app:80; }

server {
    listen 80;

    location /e1/ { proxy_pass http://lab_e1/; }
    location /e2/ { proxy_pass http://lab_e2/; }
    location /e3/ { proxy_pass http://lab_e3/; }
    location /e4/ { proxy_pass http://lab_e4/; }
    location /e5/ { proxy_pass http://lab_e5/; }
    location /e6/ { proxy_pass http://lab_e6/; }
    location /m1/ { proxy_pass http://lab_m1/; }
    location /m2/ { proxy_pass http://lab_m2/; }
    location /m3/ { proxy_pass http://lab_m3/; }
    location /m4/ { proxy_pass http://lab_m4/; }
    location /m5/ { proxy_pass http://lab_m5/; }
    location /h1/ { proxy_pass http://lab_h1/; }
    location /h2/ { proxy_pass http://lab_h2/; }
    location /h3/ { proxy_pass http://lab_h3/; }
    location /h4/ { proxy_pass http://lab_h4/; }
    location /h5/ { proxy_pass http://lab_h5/; }
#    location /articles/ { proxy_pass http://articles/; }
}

}
