version: '3.8'
services:
  api-security-easy-5:
    build: .
    container_name: api-security-easy-5
    ports:
      - "8074:80"
    volumes:
      - ./logs:/var/log/apache2
    restart: unless-stopped
    networks:
      - lab-network
      - tracking-network

networks:
  lab-network:
    driver: bridge
  tracking-network:
    external: true
