version: '3.8'

services:
  file-handling-lab:
    build: .
    container_name: file-handling-lab
    ports:
      - "8061:80"
    volumes:
      - ./logs:/var/log/apache2
    restart: unless-stopped
    networks:
      - file-handling-network
      - tracking-network

networks:
  file-handling-network:
    driver: bridge
  tracking-network:
    external: true
